// vue-typescript-eslint/src/App.vue
<script lang="tsx">
import Vue from 'vue'
import Component from 'vue-class-component'
import svgImg from './assets/react.svg'

const set = new Set()
set.add(1)
set.add(2)
set.add(3)

@Component({})
export default class App extends Vue {
  text = 'test' + [...set].join('\n')
  svgImg = svgImg
  mounted() {
    //
  }
  render(){
    return (
      <div id="app">
        <div className="css-style">css</div>
        <div className="less-style">less</div>
        <div className="scss-style">scss</div>
        <div className="stylus-style">stylus</div>
        <div className="text">{ Text }</div>
        <img className="image" src={require("./assets/vue.png")} />
        <div className="image bg-image" />
        <img className="image svg-image" src={this.svgImg} />
      </div>
    )
  }
}
</script>

<style lang="less">
@import './style/css.css';
@import './style/less.less';
@import './style/scss.scss';
@import './style/stylus.stylus';
#app {
  display: flex;
  width: 200px;
  margin: 0 auto;
  text-align: center;
  background-color: #eee;
  flex-direction: column;
  justify-content: center;
  align-content: center;
  .text {
    color: black;
  }
  .image {
    display: block;
    width: 50px;
    height: 50px;
    margin: 0 auto;
  }
  .bg-image {
    width: 100%;
    height: 60px;
    background: url('./assets/webpack.svg') no-repeat #273a41;
    background-size: 100%;
  }
  .svg-image {
    display: block;
    width: 100%;
    margin: 0 auto;
    background-color: gray;
  }
}
</style>

// react-eslint/src/App.jsx
import React, { useCallback, useMemo } from 'react'
import { useState, useEffect } from 'react'
import svgImg from './assets/react.svg'
import './App.less'

function App() {
  const [count, setCount] = useState(0)

  useEffect(() => {
    setTimeout(() => {
      setCount((val) => val + 1)
    }, 3000)
  }, [])

  const text = useMemo(() => {
    const set = new Set()
    set.add(1)
    set.add(2)
    set.add(3)
    return 'react \n' + [...set].join('\n')
  }, [])
  s
  return (
    <div id="app">
      <div className="css-style">css</div>
      <div className="less-style">less</div>
      <div className="scss-style">scss</div>
      <div className="stylus-style">stylus</div>
      <div className="text">
        {text} - {count}
      </div>
      <img className="image" src={require('./assets/vue.png')} />
      <div className="image bg-image" />
      <img className="image svg-image" src={svgImg} />
    </div>
  )
}

export default App
